on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master", "gh-pages" ]
  pull_request:
    branches: [ "master", "gh-pages" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
name: Daily Jobs
jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Run Renovate
        uses: docker://renovate/renovate
        env:
          RENOVATE_REPOSITORIES: LisinIwan/new-app
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_AUTOMERGE: false # optional, see below
          GITHUB_COM_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
