name: Renovate
on:
  push:
    branches: [ "masterx", "gh-pagesx" ]
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.118.0
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
