name: Renovate
on:
  push:
    branches: [ "master", "gh-pages", "renovate" ]
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0/15 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.238.4
        with:
          configurationFile: example/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@fd675ced9c17f1393071e1a2e685ab527e585a0c # tag=v2.5.0
        env:
          LOG_LEVEL: 'debug'
